babystats/urls.py
from django.urls import path

from . import views
app_name = 'babystats'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:category_id>/', views.detail, name='detail'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('<int:category_id>/running/<int:event_id>/', views.running, name='running'),
    path('<int:category_id>/end_event/<int:event_id>/', views.end_event, name='end_event'),
    path('<int:category_id>/create_new/', views.create_new, name='create_new'),
    path('<int:category_id>/saveme/<int:event_id>/', views.saveme, name='saveme'),
#    path('neu', views.neu, name='neu'),
    path('click', views.click, name='click'),
    # ex: /category/5/results/
    path('<int:category_id>/results/', views.results, name='results'),
    # ex: /category/5/vote/
    path('<int:category_id>/vote/', views.vote, name='vote'),

]

prod/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('babystats/', include('babystats.urls')),
]

babystats/models.py
import datetime
from django.db import models
from django.utils import timezone


class Category(models.Model):
    """Different categories are e.g. diaper change, breast feeding"""

    category_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published", default=timezone.now)

    def was_published_recently(self):
        return self.pub_date >= timezone.now - datetime.timedelta(days=1)

    def __str__(self):
        return self.category_text


class Event(models.Model):
    """A single event of an action"""

    event_text = models.ForeignKey(Category, on_delete=models.CASCADE)
    shit = models.BooleanField("Contains shit", default=False)
    mood = models.IntegerField(default=0)
    fee = models.IntegerField(default=0)
    good_day = models.BooleanField("Had a good day?", default=False)

    time_from = models.DateTimeField("Time started", default=timezone.now)
    time_to = models.DateTimeField("Time ended", default=timezone.now)

    def within_24h(self):
        if self.time_from >= timezone.now - datetime.timedelta(days=1):
            return self.time_from.isoformat()

    def shit_show(self):
        return self.shit
    def from_show(self):
        #return self.time_from.isoformat()
        return self.time_from.strftime("%m/%d %H:%M:%S")
    def to_show(self):
        return self.time_to.strftime("%m/%d %H:%M:%S")
    def __str__(self):
        return self.time_from.isoformat()

babystats/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from .models import Category, Event
from django.utils import timezone

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from django.template import loader

# Create your views here.

def index(request):
    latest_category_list = Category.objects.order_by('-pub_date')[:5]
    template = loader.get_template('babystats/index.html')
    context = {
            'latest_category_list': latest_category_list,
            }
    return HttpResponse(template.render(context, request))


def dashboard(request):
    latest_category_list = Category.objects.order_by('-pub_date')[:5]
    latest_event_list = Event.objects.order_by('-event_text')[:5]
    template = loader.get_template('babystats/dashboard.html')
    context = {
            'latest_category_list': latest_category_list,
            'latest_event_list': latest_event_list,
            }
    return HttpResponse(template.render(context, request))

def click(request):
    return HttpResponse("Click what's happening")


def detail(request, category_id):
    try:
        category = Category.objects.get(pk=category_id)
    except Category.DoesNotExist:
        raise Http404("category does not exist")
    return render(request, 'babystats/detail.html', {'category': category})


def results(request, category_id):
    response = "You're looking at the results of category %s."
    return HttpResponse(response % category_id)


def vote(request, category_id):
    return HttpResponse("You're voting on category%s." % category_id)

def running(request, category_id, event_id):
    category = get_object_or_404(Category, pk=category_id)
#    event = get_object_or_404(Event, pk=event_id)
    event = get_object_or_404(Event, pk=event_id)
    
    return render(request, 'babystats/running.html', {'category': category, 'event': event})

def saveme(request, category_id, event_id):
    print(request.POST)
    time_from = request.POST['event_from']
    time_to = request.POST['event_to']
    mood = request.POST['mood']
    print("saveme") 
    category = get_object_or_404(Category, pk=category_id)
    event = get_object_or_404(Event, pk=event_id)
    event.time_from = time_from
    event.time_to = time_to
    event.mood = mood 
#    event = category.event_set.create()

    if request.POST['action'] == 'End':
        event.save()
        return HttpResponseRedirect(reverse('babystats:dashboard'))
    else:
        event.time_to = timezone.now().strftime("%Y-%m-%d %H:%M:%S")
        event.save()
        return render(request, 'babystats/running.html', {'category': category, 'event': event})

def end_event(request, category_id, event_id):
    print(request.POST)
    time_from = request.POST['event_from']
    time_to = request.POST['event_to']
    mood = request.POST['mood']
    print("saveme") 
    category = get_object_or_404(Category, pk=category_id)
    event = get_object_or_404(Event, pk=event_id)
    event.time_from = time_from
    event.time_to = time_to
    event.mood = mood 
    event.save()
#    event = category.event_set.create()
    print(80*'-')
    #return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
    return HttpResponseRedirect(reverse('babystats:dashboard'))
#    return HttpResponseRedirect(request, 'babystats/dashboard.html', )



def create_new(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    event = category.event_set.create()

    return render(request, 'babystats/running.html', {'category': category, 'event': event})

babystats/templates/babystats/dashboard.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'babystats/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'babystats/pony.css' %}">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3pro.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-blue.css">
<h1> Baby Pony Track </h1>

{% if latest_category_list %}
    <ul>
    {% for category in latest_category_list %}
    

    <form action="{% url 'babystats:create_new' category.id  %}" method="post">
    {% csrf_token %}
    <input type="submit" value="{{ category.category_text }}">
    </form>
{% endfor %}
    </ul>
{% else %}
    <p>No categories are configured, yet. Please go to the admin page and create your categories, which you want to trace.</p>
{% endif %}

babystats/templates/babystats/detail.html
<h1>Detail page for {{ category.category_text }}</h1>
<ul>
    {% for event in category.event_set.all %}
    <li>{{ event.time_from }}</li>
    <li>{{ event.time_to }}</li>
    <li>{{ event.event_text }}</li>
    Did it contain shit? {{ event.shit }}
    <p> hello </p>
{% endfor %}
</ul>

babystats/templates/babystats/index.html
{% if latest_category_list %}
    <ul>
    {% for category in latest_category_list %}
        <li><a href="{% url 'babystats:detail' category.id %}">{{ category.category_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

babystats/templates/babystats/neu.html
<h1>Detail page for {{ category.category_text }}</h1>
<ul>
{% for event in category.event_set.all %}
    <li>{{ event.time_from }}</li>
    <li>{{ event.time_to }}</li>
    <li>{{ event.event_text }}</li>
    Did it contain shit? {{ event.shit }}
    <p> hello </p>
{% endfor %}
</ul>


<form action="{% url 'babystats:neu' %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ category.category_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <input type="radio" name="shit" id="shit" value="{{ category.event_set.shit }}">
    <label for="shit {{ forloop.counter }}">shit</label><br>
    <input type="mood" name="mood" id="mood" value="{{ category.event_set.mood }}">
    <label for="shit ">mood</label><br>
</fieldset>
<input type="submit" value="Vote">
</form>

babystats/templates/babystats/running.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'babystats/pony.css' %}">

{% if category %}
    <a href="/babystats/{{ category.id }}/">{{ category.category_text }}</a></li>
    

<form action="{% url 'babystats:saveme' category.id event.id %}" method="post">
{% csrf_token %}
<fieldset>

    <legend><h1> {{ category.category_text }} </h1></legend>
    <fieldset>
        <input type="datetime-local" name="event_from" id="event.item_from" value="{{ event.time_from }}">
        <label for="event_from">Current Start Time {{ event.time_from }}</label><br>

        <form method="POST">
            {% csrf_token %}
            <input type="button" onclick="alert" value="Now">
        </form>

    </fieldset>
<fieldset>
    <legend><h1>Time End </h1></legend>
        <input type="datetime-local" name="event_to" id="event.item_to" value="{{ event.time_to }}">
        <label for="event_to">Current Start Time {{ event.time_to }}</label><br>
</fieldset>

<fieldset>
    <legend><h1>Mood</h1></legend>
        <input type="Integer" name="mood" id="event.mood" value="{{ event.mood}}">
        <label for="mood">Current Start Time {{ event.mood }}</label><br>
</fieldset>


<input type="submit" name="action" value="Change Settings">
<input type="submit" name="action" value="End">
</form>



    </ul>
{% else %}
    <p>No categories are configured, yet. Please go to the admin page and create your categories, which you want to trace.</p>
{% endif %}

babystats/templates/babystats/running_bak.html
{% load django_bootstrap5 %}
{% bootstrap_css %}

<p> homeland park event going on</p>

<p> Current settings:</p>

<li> Event ID: {{ event.id}}</li>
<li> Time start: {{ event.from }}</li>
<li> Time to: {{ event.to}}</li>
<li> Mood: {{ event.mood }}</li>
<li> Shit: {{ event.shit }}</li>


{% if category %}
    <ul>
    <li><a href="/babystats/{{ category.id }}/">{{ category.category_text }}</a></li>
    

<form action="{% url 'babystats:running' category.id event.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>Time Start </h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <input type="datetime-local" name="event_from" id="event.from" value="{{ event.from }}">
        <label for="event">Current Start Time {{ event.from_show }}</label><br>
</fieldset>

<fieldset>
    <legend><h1>Time End</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <input type="datetime-local" name="event_to" id="event.to" value="{{ event.to }}">
        <label for="event2">Current End Time {{ event.to_show }}</label><br>
</fieldset>


<fieldset>
    <legend><h1>Mood</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <input type="int" name="event_mood" id="event" value="{{ event.mood }}">
        <label for="event3">Current Mood: {{ event.mood }}</label><br>
</fieldset>

<fieldset>
    <legend><h1>Shit</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <input type="radio" name="event_shit" id="event" value="{{ event.shit }}">
        <label for="event4"> shit {{ event.mood }}</label><br>
</fieldset>


<input type="submit" value="Change Settings">
<input type="submit" value="Change Time From">
</form>

    </ul>
{% else %}
    <p>No categories are configured, yet. Please go to the admin page and create your categories, which you want to trace.</p>
{% endif %}

babystats/templates/babystats/test.html
<h1>Detail page for </h1>
<ul>
        hallo
</ul>